"""Retrospective settings diagnostic for the Part 1 memory tool; no model calls.

Runs each single-setting change and every distinct combination of the five settings on
the 20 public scenarios. This uses knowledge of the fixture confidence scores and does
not follow the campaigns' four-decision budget, so it is not an optimizer comparison.
"""

import argparse
import itertools
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from lab.memory import Config  # noqa: E402
from lab.runner import provenance, read_json, run_scenario  # noqa: E402

REPORT = ROOT / "reports/settings-grid.json"
SUMMARY = ROOT / "reports/settings-grid.md"
AGENT_FINAL = {
    "filter_entity": True,
    "time_aware": True,
    "deduplicate": True,
    "min_confidence": 0.6,
}
SINGLE = [
    ("Baseline", {}),
    ("Subject filter only", {"filter_entity": True}),
    ("Date filter only", {"time_aware": True}),
    ("Deduplication only", {"deduplicate": True}),
    ("min_confidence = 0.6 only", {"min_confidence": 0.6}),
    ("Both filters", {"filter_entity": True, "time_aware": True}),
    ("Agent's final configuration", AGENT_FINAL),
]


def score(scenarios: list[dict], patch: dict) -> dict:
    config = Config().patch(patch)
    runs = [run_scenario(scenario, config, 1) for scenario in scenarios]
    stored = sum(run["counts"].get("storage_records", 0) for run in runs) / len(runs)
    return {"passed": sum(run["success"] for run in runs), "mean_storage_records": round(stored, 4)}


def threshold_classes(scenarios: list[dict]) -> list[float]:
    """A threshold t stores facts with confidence >= t, so only the fixture scores matter."""
    return sorted(
        {
            event["fact"]["confidence"]
            for scenario in scenarios
            for event in scenario["events"]
            if event["action"] == "write" and event["fact"].get("kind") == "fact"
        }
    )


def build() -> dict:
    scenarios = read_json(ROOT / "data/scenarios.json")
    thresholds = threshold_classes(scenarios)
    single = [
        {"label": label, "patch": patch, **score(scenarios, patch)} for label, patch in SINGLE
    ]
    names = ["min_confidence", "filter_entity", "time_aware", "deduplicate", "top_k"]
    on_off = [False, True]
    patches = [
        dict(zip(names, values, strict=True))
        for values in itertools.product(thresholds, on_off, on_off, on_off, range(1, 9))
    ]
    results = [{"patch": patch, **score(scenarios, patch)} for patch in patches]
    # Selection rule from the article: more complete scenarios, then fewer stored records.
    ranked = sorted(results, key=lambda r: (-r["passed"], r["mean_storage_records"]))
    best = ranked[0]
    best_settings = {k: v for k, v in best["patch"].items() if k != "top_k"}
    by_settings = {}
    for result in results:
        key = json.dumps({k: v for k, v in result["patch"].items() if k != "top_k"})
        by_settings.setdefault(key, set()).add((result["passed"], result["mean_storage_records"]))
    return {
        "label": (
            "Retrospective diagnostic on the 20 public development scenarios. It uses the "
            "fixture confidence scores and ignores the campaigns' decision budget; it is not "
            "a budget-matched optimizer comparison."
        ),
        "source_sha256": provenance()["source_sha256"],
        "scenario_count": len(scenarios),
        "threshold_classes": [
            {"min_confidence": t, "stores_confidence_above": prev}
            for prev, t in zip([None, *thresholds], thresholds, strict=False)
        ],
        "single_settings": single,
        "grid": {
            "configurations": len(results),
            "scenario_runs": len(results) * len(scenarios),
            "passing_all": sum(r["passed"] == len(scenarios) for r in results),
            "top_k_changes_result": any(len(v) > 1 for v in by_settings.values()),
            "best_settings": best_settings,
            "best_matches_agent_final": best_settings == AGENT_FINAL,
            "best_passed": best["passed"],
            "best_mean_storage_records": best["mean_storage_records"],
        },
        "results": results,
    }


def summary(report: dict) -> str:
    grid, n = report["grid"], report["scenario_count"]
    rows = "\n".join(
        f"| {row['label']} | `{json.dumps(row['patch'])}` | {row['passed']}/{n} | "
        f"{row['mean_storage_records']:.2f} |"
        for row in report["single_settings"]
    )
    return f"""# Settings grid: retrospective diagnostic

{report["label"]}

Generated by `uv run --frozen python scripts/settings_grid.py`. Source SHA-256:
`{report["source_sha256"]}`. Full results: [`settings-grid.json`](settings-grid.json).

## One change at a time

| Configuration | Patch | Scenarios passed | Mean stored records |
| --- | --- | ---: | ---: |
{rows}

## Every distinct combination

The fixture facts have {len(report["threshold_classes"])} distinct confidence scores, so
{len(report["threshold_classes"])} thresholds cover every distinct write behaviour. With three
on/off settings and `top_k` from 1 to 8, that is {grid["configurations"]} configurations and
{grid["scenario_runs"]:,} scenario runs.

- {grid["passing_all"]} configurations pass {n}/{n}.
- `top_k` changes the result: {"yes" if grid["top_k_changes_result"] else "no"}.
- Best under the selection rule: `{json.dumps(grid["best_settings"])}` with any `top_k`,
  {grid["best_passed"]}/{n} passed and {grid["best_mean_storage_records"]:.2f} stored records.
- Same settings as the agent's final configuration:
  {"yes" if grid["best_matches_agent_final"] else "no"}.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="Fail if saved reports are stale")
    args = parser.parse_args()
    report = build()
    text = json.dumps(report, indent=2) + "\n"
    if args.check:
        stale = REPORT.read_text() != text or SUMMARY.read_text() != summary(report)
        print("settings grid reports are stale" if stale else "settings grid reports match")
        return int(stale)
    REPORT.write_text(text)
    SUMMARY.write_text(summary(report))
    print(f"wrote {REPORT.relative_to(ROOT)} and {SUMMARY.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
